### ISSUE TITLE
预测时，input_shape改成[640，512，3]就不出结果

### ISSUE THREAD

**Issue by yjh5581** [bubbliiiing/centernet-keras#5]
因为要预测的图片长宽比都是2：1，觉得做 letterbox会造成速度慢      
程序中的 "input_shape"       : [512,512,3] 改成"input_shape"       : [640,640,3] 没问题
改成[640，512，3]就不出结果了

**Comment by bubbliiiing** [comment]
1、不会慢，都会有lattebox_image的过程
2、可能是我长方形的检测没有测试修改，细节上存在问题，使用正方形不会影响你的检测结果和速度的。

**Comment by yjh5581** [comment]
utils/utils.py
w, h = size
改成
h, w = size

**Comment by bubbliiiing** [comment]
0 0。
